Repository JJ-Anime-Group/wp-anime-review, pull requests merged in 2020-03, with the labels that each got.

#6 Upload project description file.
  Project-INFO3602.pdf
Labels: documentation

#5 Update README.md to be more descriptive.
  README.md
Labels: documentation, good first issue

#13 Make some changes to the README.md
  README.md
Labels: enhancement

#29 Merge custom roles
  .gitignore
  public/wp-content/themes/.gitignore
  public/wp-content/themes/newsup-child/functions.php
  sql/local.sql
Labels: core features, enhancement
